name: Rolling Source Build
on:
  pull_request:  ## just for testsing - delete before merge!
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  source:
    uses: ./.github/workflows/reusable-ros-tooling-source-build.yml
    with:
      github_runner_virt_env: ubuntu-latest
      ros_distro: rolling
      ros2_distro_branch: master
      ref: master
